name: terminal_ssh_mobile
description: TerminalSSH mobile client (Flutter + dartssh2)
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dartssh2: ^2.11.0
  xterm: ^4.0.0
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3
  http: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
